### PR TITLE
Replace hard coded status core with dynamic version

### LINKED ISSUE #48: Don't choke on patched Vivado versions
Currently, when using a patched Vivado version, Tapasco fails at least at two places:

> Could not find /scratch/mio/tapasco_f1/common/common_2018.2_AR71715.tcl, Vivado 2018.2_AR71715 is not supported yet! 

While this can easily be resolved by placing a symlink to the `common_2018.2.tcl` file, there is also a problem with the `tapasco_status.json` which causes Tapasco (or rather the JSON Parser) to throw an Exception and exit:

```
   "Versions"              : [{
        "Software" : "Vivado",
        "Year"     : 2018_AR71715,
        "Release"  : 2_AR71715
```

Results in:
> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('_' (code 95))

### LINKED ISSUE #83: Replace custom status core format with something well known
Candidates might be something like 
 * [Protobuf](https://developers.google.com/protocol-buffers/)
 * [FlatBuffers](https://google.github.io/flatbuffers/)
 * [Cap'n Proto](https://capnproto.org)

### PR DESCRIPTION
**Pull request by jahofmann**
* Replaces the custom, hard-coded status core format with a protobuf version
 * Easily add information to the status core and use that information from the runtime and driver
 * Adds necessary dependencies
 * Custom statically-linked rust executable is used to translate the JSON generated by the TaPaSCo flow to a protobuf binary
 * All of the examples are fixed and tested
 * The memory map as seen from user space is now completely platform independent. The driver is used to translate the virtual addresses to device specific ones.
 * Closes #48 
 * Closes #83

### CODE REVIEW

File: runtime/kernel/dma/blue_dma.c [hunk 1]
```diff
@@ -39,8 +39,7 @@
 irqreturn_t blue_dma_intr_handler_read(int irq, void * dev_id)
 {
 	struct dma_engine *dma = (struct dma_engine *)dev_id;
-	struct platform *p = &dma->dev->cls->platform;
-	volatile uint32_t* msix_ack = (volatile uint32_t*) (dma->dev->mmap.plat + ((0x500000 + 0x8120) - p->plat.base));
+	volatile uint32_t* msix_ack = (volatile uint32_t*) (dma->dev->mmap.plat + 0x28120);
```
Comment (m-ober) [inline runtime/kernel/dma/blue_dma.c]: Are these addresses supposed to stay hardcoded?

Comment (jahofmann) [reply runtime/kernel/dma/blue_dma.c]: No, in fact they are not! Good catch

Comment (jahofmann) [reply runtime/kernel/dma/blue_dma.c]: Solved that issue in 68df96a
